- name: Create Folder
  ansible.builtin.file:
    path: "/home/{{item.homedir}}"
    state: directory
    mode: '0755'

- name: Create Groups
  ansible.builtin.group:
    name: "{{item.group}}"
    state: present

- name: Create User
  ansible.builtin.user:
    name: "{{item.name}}"
    shell: /bin/bash/
    groups: "{{item.group}}"
    append: yes
    home: "/home/{{item.homedir}}"
